[versions]
opencsvVersion = "5.6"
icasamvlVersion = "2.20220524.0"

[libraries]
opencsv = { module = "com.opencsv:opencsv", version.ref = "opencsvVersion" }
icasamvl = { module = "org.agmip.resources:icasa-mvl", version.ref = "icasamvlVersion" }

[bundles]

[plugins]
